server:
  port: 80

urls:
  Fund-Increase: http://fundgz.1234567.com.cn/js/FUND_CODE.js
  Access-Token: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  Menu-Generate: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN
  #获取到的 appid
  Appid: ${YOUR_APPID}
  #获取到的 AppSecret
  App-Secret: ${YOUR_APPSECRET}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: >
    com.huiaong.bulbasau.entity

logging:
  config: classpath:Logback-spring.xml